# netlify.toml

[build]
  command = "npm run build"
  publish = "dist" # Ruta de la carpeta de archivos estáticos generados por Nuxt.js

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
